const UPDATE_EXPRESSION = 'UPDATE_EXPRESSION';
const UPDATE_OUTCOME = 'UPDATE_OUTCOME';
const UPDATE_CHAT_SESSION = 'UPDATE_CHAT_SESSION';

export {
    UPDATE_EXPRESSION,
    UPDATE_OUTCOME,
    UPDATE_CHAT_SESSION
};
